name: PHP Composer

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  # Build the assets.
  validate:
    runs-on: ubuntu-latest
    name: Composer Validate

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate


  build:
    needs: validate
    name: Composer Build / PHPCS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: composer install --no-progress

      # Run sniffing and validation.
      - name: Run PHP code sniffer
        run: composer run-script code-sniff
  
  deploy:
    needs: [validate, build]
    if: always()
    name: Deploy to Master
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Sync Action
        uses: wei/git-sync@v2.0.0
        with:
          source_repo: https://github.com/${GITHUB_REPOSITORY}
          source_branch: "refs/remotes/source/default"
          destination_repo: https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          destination_branch: "refs/heads/master"

          