name: PHP Composer

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  # Build the assets.
  validate:
    runs-on: ubuntu-latest
    name: Composer Validate

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate


  build:
    needs: validate
    name: Composer Build / PHPCS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: composer install --no-progress

      # Run sniffing and validation.
      - name: Run PHP code sniffer
        run: composer run-script code-sniff
  
  deploy:
    needs: [validate, build]
    if: always()
    name: Deploy to Master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Deploy to master branch
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: Deploy changes to default.
          name: Pantheon SE Bot
          email: se@pantheon.io
