name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build the assets.
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  # Run sniffing and validation.
  test:
    steps:
      - uses: actions/checkout@v2
  
      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
  
      - name: Run PHP code sniffer
        run: composer run-script code-sniff
      
  deploy:
      steps:
        - uses: actions/checkout@v2

        - name: Deploy into default.
          run: git checkout default; git rebase master; git push;