name: PHP Composer

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]

jobs:
  # Build the assets.
  validate:
    runs-on: ubuntu-latest
    name: Composer Validate

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate


  build:
    needs: validate
    name: Composer Build / PHPCS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: composer install --no-progress

      # Run sniffing and validation.
      - name: Run PHP code sniffer
        run: composer run-script code-sniff
  
  deploy:
    needs: [validate, build]
    if: always()
    name: Deploy to Master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "default"
          TO_BRANCH: "master"